[profile.default]
src = "src"
out = "out"

[fmt]
sort_imports = true
number_underscore = "thousands"
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
